name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Checkout
        uses: actions/checkout@v3
      - name: Login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login ${{ secrets.DOCKER_REGISTRY }} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build
        run: docker build -t disguard .
      - name: Tag
        run: docker tag disguard ${{ secrets.DOCKER_REGISTRY }}/disguard
      - name: Push
        run: docker push ${{ secrets.DOCKER_REGISTRY }}/disguard
